service: sqs-worker-service

provider:
  name: aws
  runtime: nodejs20.x
  stage: prod
  region: us-east-1

resources:
  Resources:
    OrdersQueue:
      Type: AWS::SQS::Queue

functions:
  processOrder:
    handler: src/functions/process-order.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [OrdersQueue, Arn]
